# All paths should be populated as a relative path from the repository root
[2021]
dispatch_list = "input/dispatch_lists/Dispatch list 2021-22.xlsx"

    [2021.current_year]
    coded_data_file = "input/downloaded/2021/ReadingRecoveryEvalu_DATA_2021.csv"
    label_data_file = "input/downloaded/2021/ReadingRecoveryEvalu_DATA_LABELS_2021.csv"

    [2021.previous_year]
    coded_data_file = "input/downloaded/2021/ReadingRecoveryEvalu_DATA_2020.csv"
    label_data_file = "input/downloaded/2021/ReadingRecoveryEvalu_DATA_LABELS_2020.csv"

[2022]
dispatch_list = "input/dispatch_lists/Dispatch list 2022-23.xlsx"

    [2022.current_year]
    coded_data_file = "input/downloaded/2022/ReadingRecoveryEvalu_DATA_2022.csv"
    label_data_file = "input/downloaded/2022/ReadingRecoveryEvalu_DATA_LABELS_2022.csv"

    [2022.previous_year]
    coded_data_file = "input/downloaded/2022/ReadingRecoveryEvalu_DATA_2021.csv"
    label_data_file = "input/downloaded/2022/ReadingRecoveryEvalu_DATA_LABELS_2021.csv"

[2023]
dispatch_list = "input/dispatch_lists/Dispatch list 2023-24.xlsx"

    [2023.current_year]
    coded_data_file = "input/downloaded/2023/ReadingRecoveryEvalu_DATA_2023.csv"
    label_data_file = "input/downloaded/2023/ReadingRecoveryEvalu_DATA_LABELS_2023.csv"

    [2023.previous_year]
    coded_data_file = "input/downloaded/2023/ReadingRecoveryEvalu_DATA_2022.csv"
    label_data_file = "input/downloaded/2023/ReadingRecoveryEvalu_DATA_LABELS_2022.csv"
