[school]
template = "input/templates/2021/2021-22_template.docx"
n_tables = 7
dispatch_list = "input/dispatch_lists/Dispatch list 2021-22.xlsx"

### The below aren't yet implemented and just contain placeholder values!
# Do not use the school template for 'centre' or 'national' report production
[centre]
template = "input/templates/2021/2021-22_template.docx"
n_tables = 999

[national]
template = "input/templates/2021/2021-22_template.docx"
n_tables = 999
