client_id = ""
client_secret=""
tenant_id=""
send_emails_as=""
# Note: username is with `@ucl.ac.uk`, e.g. sejjpia@ucl.ac.uk
username = ""
scope = 'https://outlook.office.com/.default'
server = 'outlook.office365.com'
